apiVersion: v1
kind: Service
metadata:
  name: python-k8s-sample-service
  labels:
    app: python-k8s-sample-label
spec:
  type: LoadBalancer 
  ports:
  - port: ${PORT}
    targetPort: ${PORT}
    protocol: TCP
  selector:
    app: python-k8s-sample-label